# Generated by Django 5.2.4 on 2025-07-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(max_length=100)),
                ('last_location', models.CharField(max_length=100)),
                ('estimated_delivery', models.DateField()),
            ],
        ),
    ]
