# Generated by Django 5.2.4 on 2025-09-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_shipment_destination_shipment_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
