# Generated by Django 5.2.4 on 2025-09-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_shipment_email_shipment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='phone',
        ),
    ]
