# Generated by Django 5.2.4 on 2025-09-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_shipment_email_remove_shipment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
