# Generated by Django 5.2.4 on 2025-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_shipment_date_shipment_email_shipment_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingupdate',
            options={'ordering': ['-timestamp']},
        ),
    ]
