# Generated by Django 5.2.4 on 2025-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_remove_shipment_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
