# Generated by Django 5.2.4 on 2025-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_shipment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingupdate',
            options={},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='stop_position',
        ),
        migrations.AddField(
            model_name='shipment',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
