# Generated by Django 5.2.4 on 2025-09-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_alter_trackingupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingupdate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='estimated_delivery',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='shipment',
            name='stop_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50),
        ),
    ]
