# Generated by Django 5.2.4 on 2025-09-25 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_trackingupdate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='stop_position',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
